[project]
name = "gh-menu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "requests>=2.32.5",
    "rumps>=0.4.0",
]
